### ISSUE TITLE
Could you tell me how I can get synthesize ?

### ISSUE THREAD

**Issue by kyungtae** [HaozheJasper/CBRL_KDD22#1]
Thanks for this great work.
I'd like to reproduce your work from the source code, 
but I couldn't find the 'synthesize' or 'YewuSampler2'.

Could you tell me where could I get that module ?

https://github.com/HaozheJasper/CBRL_KDD22/blob/main/python/auction_simulator/envs/auction_market.py#L25

from synthesize import YewuSampler2, find_oracle

**Comment by Yufei-Wang99** [comment]
I'm facing the same problem now, any solutions so far?

**Comment by HaozheJasper** [comment]
Synthesizing scripts are left blank for your own implementation. You can now check syn_cbrl.zip for a reference implementation.
