### ISSUE TITLE
Lacking data when reproducing the result

### ISSUE THREAD

**Issue by Yufei-Wang99** [HaozheJasper/CBRL_KDD22#2]
Thanks for sharing your precious work.
When running the CBRL.sh, there's an error suggesting missing data
```
FileNotFoundError: [Errno 2] No such file or directory: '../data/yewu-data/all0221/data_meta_all_f.pkl'
```
I know that the real data is not being released, but is there any simulated data that can be used for running the code?

**Comment by HaozheJasper** [comment]
Check the Readme. The example synthetic environment is directly runnable.
